### ISSUE TITLE
Windows 8 - VirtualBox fail. Wordcamp Workshop

### ISSUE THREAD

**Issue by tsipilai** [Seravo/wordpress#10]
Result Code: 
E_FAIL (0x80004005)
Component: 
Console
Interface: 
![win8](https://cloud.githubusercontent.com/assets/3884807/7550155/f7742dfc-f65f-11e4-9b21-cb8e06f6d11a.png)
![win8_2](https://cloud.githubusercontent.com/assets/3884807/7550160/17095de0-f660-11e4-913e-fb8964782a42.png)

IConsole {8ab7c520-2442-4b66-8d74-4ff1e195d2b6}

**Comment by onnimonni** [comment]
Hey!

Thanks for attending the workshop and I'm really sorry to see this failing.

This problem seems unrelated into this project and a windows/bios problem instead.

Could you try this: https://forums.virtualbox.org/viewtopic.php?f=6&t=52191
=> So basically many people are having problems with virtualbox in windows when hyper-v is enabled

**Comment by ottok** [comment]
Windows docs at https://seravo.com/docs/development/how-to-install/#windows-cygwin were improved in commit https://github.com/Seravo/docs/commit/81f3c6a1fab881370b2a6f798022faeaa45cfc80 but the docs still don't cover Hyper-V issues nor is there a section on how to do it using PowerShell in latest Windows versions. 

Please test our Vagrant box on different Windows setups and extend docs (or fine tune Vagrantfile) as needed. Primary assignee @VeetiYliHemmo with maybe some help from @nasusa as well.

Low priority.

**Comment by ottok** [comment]
We have not encountered this issue for a long while, thus assuming it is fixed or invalid. Closing issue.
