### ISSUE TITLE
Enable ext-zip extension for PHP (Enhancement)

### ISSUE THREAD

**Issue by joonamakinen** [Seravo/wordpress#199]
Similar to mongodb issue earlier [https://github.com/Seravo/wordpress/issues/184](https://github.com/Seravo/wordpress/issues/184), it's for a bit more tailored applications. In this case, I tried installing Magento and only thing missing from Seravo's PHP is `ext-zip`. 

Ideally, Magento would in a subfolder with WordPress at web root to enable Magento API integration. But alas, one PHP extension is missing.

![image](https://user-images.githubusercontent.com/72403821/193234686-550832c7-5d10-4e1f-894e-4b5075113183.png)

![image](https://user-images.githubusercontent.com/72403821/193234591-95927d2c-d539-4b56-825c-868c6dfdb0ad.png)

**Comment by ypcs** [comment]
Thanks for the feedback!

Is this in production, staging or development (Vagrant/Docker) environment? For PHP8.1 this module was missing for some time, the issue has since been fixed, and is rolling out. 

If this is related to production/staging instance, you can contact our customer support via email (help@seravo.com), so we can roll-out this to your specific site instantly.

If this is related to development (Vagrant/Docker) we can check which version should fix the issue. (Available modules can be listed with `php -m`.)

(Our internal reference: afd32701)

**Comment by joonamakinen** [comment]
The instance in question is a production environment with PHP8.1 indeed. Good to hear it's rolling out!

php -m, what do you know, it has zip

```
[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
igbinary
imagick
imap
intl
json
ldap
libxml
mbstring
memcache
mongodb
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
redis
Reflection
session
shmop
SimpleXML
soap
sockets
sodium
SPL
sqlite3
ssh2
standard
sysvmsg
sysvsem
sysvshm
tideways
tidy
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

**Comment by ypcs** [comment]
Great! Closing this, as the bug has been fixed earlier.
