### ISSUE TITLE
Review Laravel test system: replacement for rspec+phantomjs?

### ISSUE THREAD

**Issue by ottok** [Seravo/wordpress#80]
Check this our https://laravel.com/docs/5.6/dusk

**Comment by k1sul1** [comment]
Or you could use Puppeteer: https://github.com/GoogleChrome/puppeteer

https://try-puppeteer.appspot.com/
![image](https://user-images.githubusercontent.com/2719615/36063957-a5e8da30-0e8c-11e8-930f-aa5ceb1750a3.png)

Add in https://github.com/mapbox/pixelmatch and you have visual regression tests. Would be nice to know if a commit that changed one line resulted in a 10% difference in rendered page, because that probably isn't intentional.

**Comment by ottok** [comment]
We are currently testing a new Codeception based testing system

**Comment by ottok** [comment]
Our new test system based on Codeception and headless Chrome as now been widely adopted and seems to solve all previous issues. Visual regression testing is done via our own custom system that works in concert with Codeception.

![image](https://user-images.githubusercontent.com/668724/53626735-3bfb1f00-3c0f-11e9-9770-74789afb4f08.png)
