### ISSUE TITLE
Refactor new box bootstrapping

### ISSUE THREAD

**Issue by ypcs** [Seravo/wordpress#89]
This is just for tracking the process of refactoring how new development environment gets initialized.

At least issue #88 is related - we should try to drop triggers & replace all use-cases using custom scripting inside the box so that image becomes a little more generic.

Also, let's try to drop `vagrant-hostsupdater`. We have some plans for this already.

**Comment by ottok** [comment]
This was done in https://seravo.com/docs/get-started/release-notes/#vagrant-box-seravowordpress-2019051300 and polished in later releases. We also have a Docker image available now. I will close this issue and open new issues about smaller details to finalize.

Since the network structure of Docker on Mac, we cannot replace vagrant-hostsupdater with Avahi/Bonjour as documented in #126.
